language: bash
sudo: true

os:
  - linux
dist: 
  # - precise
  - trusty
  # - xenial

before_install:
  - sudo add-apt-repository -y ppa:openafs/stable
  - sudo apt-get update -qq

  # Installing Linux Headers
  - sudo apt-cache search linux-headers-
  - sudo apt-get -y install -f linux-headers-$(uname -r)
  - sudo apt-get -y install -f linux-headers-generic 

  - sudo apt-get install -y openafs-client openafs-modules-dkms openafs-krb5 krb5-user krb5-config


script:  
  # Set up openafs configurations
  - echo cs.stanford.edu | sudo tee /etc/openafs/ThisCell
  - sudo wget --no-check-certificate --output-document=/etc/openafs/CellServDB http://grand.central.org/dl/cellservdb/CellServDB

  - sudo service openafs-client force-start

  - cd /afs
  - ls
  - cd cs.stanford.edu
  - ls