dist: precise

sudo: required

language: ruby

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - libfreeimage-dev
    - libqt5webkit5-dev

install: true

script:
  - ruby -version